[theme]
primaryColor = "#17324D"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F5F7"
textColor = "#17324D"
font = "sans serif"

[server]
runOnSave = true

[browser]
gatherUsageStats = false
